services:
  - type: web
    name: portfolio-window-theme
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_APP_EMAILJS_SERVICE_ID
        sync: false
      - key: VITE_APP_EMAILJS_TEMPLATE_ID
        sync: false
      - key: VITE_APP_EMAILJS_PUBLIC_KEY
        sync: false
